services:
  rails:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: song-list-rails
    container_name: song-list-rails
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      - RAILS_ENV=production
    volumes:
      - public:/app/public
  
  rails-nginx:
    container_name: song-list-rails-nginx
    build:
      context: ./backend/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 54020:80
    depends_on:
      - rails
    volumes:
      - public:/app/public

  sidekiq:
    container_name: song-list-sidekiq
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - RAILS_ENV=production
    command: bundle exec sidekiq
    depends_on:
      - redis

  next:
    container_name: song-list-next
    image: song-list-next
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rails

  next-nginx:
    container_name: song-list-next-nginx
    build:
      context: ./frontend/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 54030:80
    depends_on:
      - next

  db:
    image: postgres:15.1-alpine
    restart: always
    container_name: song-list-postgres
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: song_list_production

  redis:
    image: redis:alpine
    container_name: song-list-redis
    restart: always
    volumes:
      - redis-data:/var/lib/redis

volumes:
  database:
  public:
  redis-data:
