plugins: rubocop-rails

AllCops:
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - "db/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
  SuggestExtensions: false
  NewCops: enable

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Style/Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false
Security/Open:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Layout/LineLength:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Rails/HelperInstanceVariable:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
