# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.4.6'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '8.0.3'

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem 'sprockets-rails', '3.5.2'

# Use postgresql as the database for Active Record
gem 'pg', '1.6.2'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '7.0.4'

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem 'importmap-rails', '2.2.2'

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
# gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
# gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem 'jbuilder', '2.14.1'

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', '2.0.6', platforms: %i[mingw mswin x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '1.18.6', require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', '1.11.0', platforms: %i[mri mingw x64_mingw]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem 'rubocop-rails', '2.33.4', require: false
  gem 'web-console', '4.2.1'

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem 'capybara', '3.40.0'
  gem 'factory_bot_rails', '6.5.1'
  gem 'simplecov', '0.22.0', require: false
  gem 'webdrivers', '5.2.0'
end

# View
gem 'haml', '6.3.0'
gem 'haml-rails', '2.1.0'

# ENV
gem 'dotenv-rails', '3.1.8', groups: %i[development test]

# CORS
gem 'rack-cors', '3.0.0'

# ログイン
gem 'devise', '4.9.4'
gem 'devise-i18n', '1.15.0'

# Youtube
gem 'google-apis-youtube_v3', '0.57.0'

# テスト
gem 'rspec-rails', '8.0.2', groups: %i[development test]

# enumsの値を日本語化
gem 'enum_help', '0.0.20'

# XML解析
gem 'nokogiri', '1.18.10'

# ページング
gem 'kaminari', '1.2.2'

# GCS
gem 'google-cloud-storage', '1.57.0'

# スクレイピング
gem 'selenium-webdriver', '4.35.0'

# slackエラー通知
gem 'exception_notification', '5.0.1'

# 定期実行
gem 'sidekiq-scheduler', '6.0.1'
