export enum TestID {
  TEST = 'test',
  HOME = 'home',
  INQUIRY = 'inquiry',
  CHANNELS_INDEX = 'channels-index',
  CHANNELS_SHOW = 'channels-show',
  MAINTENANCE_CHANNELS_SHOW = 'maintenance-channels-show',
  MAINTENANCE_HOME = 'maintenance-home',
  HOME_CHANNELS_BUTTON = 'home-channels-button',
  CUSTOM404 = 'custom404',
  CUSTOM500 = 'custom500',
  NAVBAR = 'navbar',
  PROFILE_BUTTON = 'profile-button',
  CHANNELS = 'channels',
  CHANNEL = 'channel',
  VIDEOS = 'videos',
  VIDEO = 'video',
  VIDEOS_SEARCH = 'videos-search',
  VIDEO_SEARCH_DETAIL_BUTTON = 'video-search-detail-button',
  SONG_ITEMS = 'song-items',
  SONG_ITEM = 'song-item',
  SONG_ITEMS_SEARCH = 'song-items-search',
  SONG_ITEMS_SEARCH_DETAIL_BUTTON = 'song-items-search-detail-button',
  SONG_LIST_ITEM = 'song-list-item',
}
