export enum TestID {
  TEST = 'test',
  HOME = 'home',
  HOME_CHANNELS_BUTTON = 'home-channels-button',
  CUSTOM404 = 'custom404',
  CUSTOM500 = 'custom500',
  NAVBAR = 'navbar',
  PROFILE_BUTTON = 'profile-button',
  CHANNELS = 'channels',
  CHANNEL = 'channel',
  VIDEOS = 'videos',
  VIDEO = 'video',
  SONG_ITEMS = 'song-items',
  SONG_ITEM = 'song-item',
}
