name: Build Frontend for Release
on:
  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: |
            ghcr.io/${{ github.repository }}-frontend:1.0.${{ github.run_number }}
            ghcr.io/${{ github.repository }}-frontend:latest
          path: "./frontend"
          cache-registry: ghcr.io/${{ github.repository }}-frontend:buildcache
