name: Build Frontend for Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: |
            ghcr.io/${{ github.repository }}-frontend:1.0.${{ github.run_number }}
            ghcr.io/${{ github.repository }}-frontend:latest
          path: "./frontend"
          build-args: |
            BACKEND_HOST=http://song-list-backend.default.svc.cluster.local:3000
