name: Build Backend for Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: |
            ghcr.io/${{ github.repository }}-backend:1.0.${{ github.run_number }}
            ghcr.io/${{ github.repository }}-backend:latest
          path: "./backend"

  backend-ubuntu:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: |
            ghcr.io/${{ github.repository }}-backend:ubuntu-1.0.${{ github.run_number }}
          path: "./backend"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./backend
          file: ./backend/Dockerfile.ubuntu
          tags: |
            ghcr.io/${{ github.repository }}-backend:ubuntu-1.0.${{ github.run_number }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}-backend:ubuntu-buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}-backend:ubuntu-buildcache,mode=max
