name: Build Backend for Release
on:
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: |
            ghcr.io/${{ github.repository }}-backend:1.0.${{ github.run_number }}
            ghcr.io/${{ github.repository }}-backend:latest
          path: "./backend"
          cache-registry: ghcr.io/${{ github.repository }}-backend:buildcache
