name: Build for Staging
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    environment: staging # 管理者の承認を必要とする
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: |
            ghcr.io/${{ github.repository }}-backend:main-${{ github.sha }}-${{ github.run_number }}
          path: "./backend"
          cache-registry: ghcr.io/${{ github.repository }}-backend:buildcache
          build-args: |
            BACKEND_HOST=http://stg-song-list-backend.default.svc.cluster.local:3000
  backend-main:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: |
            ghcr.io/${{ github.repository }}-backend:main-${{ github.sha }}-${{ github.run_number }}
          path: "./backend"
          cache-registry: ghcr.io/${{ github.repository }}-backend:buildcache
          build-args: |
            BACKEND_HOST=http://stg-song-list-backend.default.svc.cluster.local:3000

  frontend:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    environment: staging # 管理者の承認を必要とする
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: |
            ghcr.io/${{ github.repository }}-frontend:main-${{ github.sha }}-${{ github.run_number }}
          path: "./frontend"
          cache-registry: ghcr.io/${{ github.repository }}-frontend:buildcache
          build-args: |
            BACKEND_HOST=http://stg-song-list-backend.default.svc.cluster.local:3000
  frontend-main:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
          tags: |
            ghcr.io/${{ github.repository }}-frontend:main-${{ github.sha }}-${{ github.run_number }}
          path: "./frontend"
          cache-registry: ghcr.io/${{ github.repository }}-frontend:buildcache
          build-args: |
            BACKEND_HOST=http://stg-song-list-backend.default.svc.cluster.local:3000
