name: Build for Staging
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: piny940
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./backend
          file: ./backend/Dockerfile
          tags: |
            ghcr.io/piny940/song-list-backend:main-${{ github.sha }}-${{ github.run_number }}
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: piny940
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./frontend
          build-args: |
            BACKEND_HOST=http://stg-song-list-backend.default.svc.cluster.local:3000
          file: ./frontend/Dockerfile
          tags: |
            ghcr.io/piny940/song-list-frontend:main-${{ github.sha }}-${{ github.run_number }}
